### ISSUE TITLE
johnny.cache.enable() and Fabric don't play well together

### ISSUE THREAD

**Issue by roxeteer** [jmoiron/johnny-cache#23]
If I have `from johnny.cache import enable; enable()` in the project root `__init__.py`, calling the `fab` command fails because `DJANGO_SETTINGS_MODULE` is undefined.

```
$ fab
Traceback (most recent call last):
  File "/my/project/path/venv/src/fabric/fabric/main.py", line 639, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/my/project/path/venv/src/fabric/fabric/main.py", line 163, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/my/project/path/fabfile.py", line 8, in <module>
    from my_project.util.deploy import crontab as crontab_tools
  File "/my/project/path/my_project/__init__.py", line 2, in <module>
    from johnny.cache import enable
  File "/my/project/path/venv/lib/python2.7/site-packages/johnny/cache.py", line 14, in <module>
    from johnny import settings
  File "/my/project/path/venv/lib/python2.7/site-packages/johnny/settings.py", line 5, in <module>
    from django.core.cache import get_cache, cache
  File "/my/project/path/venv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 76, in <module>
    if not settings.CACHES:
  File "/my/project/path/venv/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/my/project/path/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
    raise ImportError("Settings cannot be imported, because environment variable %s is undefined." % ENVIRONMENT_VARIABLE)
ImportError: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
```

I have johnny-cache 1.4 and Fabric 1.6.0.

**Comment by roxeteer** [comment]
I found out that there's a way to get Fabric set up Django properly which also fixes this problem. In the `fabfile.py`:

```
from fabric.contrib import django
django.project('my_project')
django.settings_module('my_project.settings')
```
